name: Deploy to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.html'   
      - 'images/**'     

env:
  BUCKET_NAME: "${{ secrets.BUCKET_NAME }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  GITHUB_REF: "main"
  CLOUDFRONT_DISTRIBUTION_ID: "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"  
  AWS_ROLE_TO_ASSUME: "${{ secrets.AWS_ROLE_TO_ASSUME }}"
  AWS_ROLE_SESSION_NAME: "${{ secrets.AWS_ROLE_SESSION_NAME }}"
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync repository to S3
      run: |
        aws s3 sync . s3://${{ env.BUCKET_NAME }} --delete --exclude ".git/**" --exclude ".github/**" --exclude "README.md" --exclude "tf/**"
      
    - name: Invalidate CloudFront cache
      if: success()
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"